[package]
name = "avr_test"
version = "0.1.0"
edition = '2021'

[dependencies]
avr-std-stub = "1.0"
avr_delay = { git = "https://github.com/avr-rust/delay" }
definitions = { path = "definitions" }

[profile.release]
lto = true
